"""update customer schema

Revision ID: 22cbe1496676
Revises: c175cd95a8bf
Create Date: 2026-04-04 02:44:10.275713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22cbe1496676'
down_revision: Union[str, Sequence[str], None] = 'c175cd95a8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_login_credentials',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customer_login_credentials_customer_id'), 'customer_login_credentials', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_login_credentials_customer_id'), table_name='customer_login_credentials')
    op.drop_table('customer_login_credentials')
    # ### end Alembic commands ###
