"""added vendor login tables

Revision ID: 50fdf0eebfda
Revises: a1b2c3d4e5f6
Create Date: 2026-04-10 05:34:54.898572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50fdf0eebfda'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_login_credentials',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_vendor_login_credentials_vendor_id'), 'vendor_login_credentials', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_login_credentials_vendor_id'), table_name='vendor_login_credentials')
    op.drop_table('vendor_login_credentials')
    # ### end Alembic commands ###
