"""add vendor image

Revision ID: 7e31a8328dd8
Revises: 22cbe1496676
Create Date: 2026-04-04 04:33:57.215892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e31a8328dd8'
down_revision: Union[str, Sequence[str], None] = '22cbe1496676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'image_url')
    # ### end Alembic commands ###
