"""add_session_token

Revision ID: bb1d13b3873c
Revises: 7e31a8328dd8
Create Date: 2026-04-06 12:40:56.725428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1d13b3873c'
down_revision: Union[str, Sequence[str], None] = '7e31a8328dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_login_credentials', sa.Column('session_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_login_credentials', 'session_token')
    # ### end Alembic commands ###
